---
# tasks file for linux_upgrade_rhel8_to_rhel9
- name: Run leapp preupgrade
  block:
  - name: remove kernel modules, which are not present in RHEL9
    modprobe:
      name: "{{ item }}"
      state: absent
    loop:
      - floppy
      - pata_acpi
  
  - name: nmcli connection migrate
    command: "nmcli connection migrate"
    register: nmcli_connection_migrate_result

  - name: upgrade crypto policies
    command: "update-crypto-policies --set LEGACY"
    register: update_crypto_policies_result

  - name: print nmcli_connection_migrate_result
    debug: 
      var=nmcli_connection_migrate_result
    when: print_debug

  - name: print update_crypto_policies_result
    debug: 
      var=update_crypto_policies_result
    when: print_debug
    
  - name: Make sure remote root login is disabled
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'

  - name: Make sure /var/log/leapp exist
    file:
      dest: /var/log/leapp
      state: directory

  #- name: copy answerfile to /var/log/leapp
  #  copy:
  #    src: answerfile
  #    dest: /var/log/leapp/answerfile

  - name: leapp preupgrade --target 9.3
    command: "/usr/bin/leapp preupgrade --target 9.3"
    register: leapp_preupgrade_result
    async: 5000
    poll: 30

  - name: print leapp_preupgrade result
    debug: 
      var=leapp_preupgrade_result

  #rescue:
  #  - debug:
  #      msg: "!!!leap preupgrade failed!!!"
