---
# vars file for ms_devops_setup
vgs: 'appvg'
pvs: '/dev/sdc'
pvs_rhel8: '/dev/sdc'
lvs:
  dock_lv:
    size: 15g
    fs_type: xfs
    mount_point: /var/lib/docker
  agent_lv:
    size: 30g
    fs_type: xfs
    mount_point: /opt/agentbuilds

software_list:
  - azure-cli
  - rh-nodejs14
  - powershell
  - java-11-openjdk
  - java-11-openjdk-devel
  - java-11-openjdk-headless
  - java-1.8.0
  - java-1.8.0-openjdk-devel
  - javamail
  - javassist
  - kubectl
  - docker-ce
software_list_rhel8_rhel9:
  - azure-cli
  - powershell
  - java-17-openjdk
  - java-17-openjdk-devel
  - java-17-openjdk-headless
  - java-1.8.0
  - java-1.8.0-openjdk-devel
  - dotnet-host
  - kubectl
  - git
  - docker-ce
software_moduled_rhel8_rhel9:
  nodejs:
    ver: 18
  ruby:
    ver: 3.1
  maven:
    ver: 3.8
repo_list_rhel8_rhel9:
  - COMPANY_Custom_Software_RHEL{{ ansible_distribution_major_version }}_Docker-CE-RHEL{{ ansible_distribution_major_version }}
  - COMPANY_Custom_Software_RHEL{{ ansible_distribution_major_version }}_Microsoft-RHEL{{ ansible_distribution_major_version }}
  - COMPANY_Custom_Software_RHEL{{ ansible_distribution_major_version }}_terraform-rhel{{ ansible_distribution_major_version }}
  - COMPANY_Custom_Software_RHEL7_Kubernetes
ssl_certs:
  - COMPANY_ROOT.pem.cer
  - COMPANY_Policy.pem.cer
  - COMPANY_Issue.pem.cer
devops_user: selfhosted
devops_group: selfhosted
proxy_url: http://proxy_address
libcurl_conf: /etc/ld.so.conf.d/libcurl-httpd24.conf
libcurl_path: /opt/rh/httpd24/root/usr/lib64/
default_java: java-11-openjdk.x86_64
default_java_rhel8: java-17-openjdk.x86_64
apache_maven: apache-maven-3.6.3-bin.tar.gz
apache_maven_dir: apache-maven-3.6.3
azure_functions_cli: Azure.Functions.Cli.linux-x64.3.0.3568.zip
https_proxy: http://185.46.212.88:443/
http_proxy: http://185.46.212.88:80/
no_proxy: localhost,.europa.internal,127.0.0.1,10.0.0.0/8,172.0.0.0/16,192.168.0.0/16
cyberarkadim_install: RHELinux-Intel64-Rls-v11.2.tgz
terraform_versions:
  - 0.12.31
  - 0.13.7
  - 0.14.11
  - 1.1.3
  - 1.2.7
  - 1.3.10
  - 1.3.9
  - 1.4.7
  - 1.5.7
  - 1.6.1
  - 1.6.6
  - 1.7.3

